stages:
  prepare:
    cmd: python Code/prepare.py
    deps:
    - Code/prepare.py
    - Data/fer2013.csv
    params:
    - prepare.selected_emotions
    outs:
    - Data/prepared_data/x_test.pkl
    - Data/prepared_data/x_train.pkl
    - Data/prepared_data/x_val.pkl
    - Data/prepared_data/y_test.pkl
    - Data/prepared_data/y_train.pkl
    - Data/prepared_data/y_val.pkl
  train:
    cmd: python Code/train.py
    deps:
    - Code/train.py
    - Data/prepared_data/x_train.pkl
    - Data/prepared_data/x_val.pkl
    - Data/prepared_data/y_train.pkl
    - Data/prepared_data/y_val.pkl
    params:
    - train.activation_func
    - train.batch_size
    - train.class_num
    - train.conv2d_kernels
    - train.conv2d_units
    - train.dense_units
    - train.epochs
    - train.image_size
    - train.learning_rate
    - train.pool_sizes
    outs:
    - Model/model.h5
    - Plots/accuracy.png
    - Plots/loss.png
  evaluate:
    cmd: python Code/evaluate.py
    deps:
    - Code/evaluate.py
    - Data/prepared_data/x_test.pkl
    - Data/prepared_data/y_test.pkl
    params:
    - evaluate.selected_emotions
    metrics:
    - Metrics/metrics.json
