stages:
  prepare:
    cmd: python Code/prepare.py
    deps:
    - Code/prepare.py
    - Data/fer2013.csv
    params:
    - prepare.selected_emotions
    outs:
    - Data/prepared_data/train
    - Data/prepared_data/val
    - Data/prepared_data/test
  train:
    cmd: python Code/train.py
    deps:
    - Code/train.py
    - Data/prepared_data/train
    - Data/prepared_data/val
    params:
    - train.classes
    - train.activation_func
    - train.batch_size
    - train.class_num
    - train.conv2d_kernels
    - train.conv2d_units
    - train.dense_units
    - train.epochs
    - train.image_size
    - train.learning_rate
    - train.pool_sizes
    - train.dropout
    outs:
    - Model/model.tf.index
    - Plots/accuracy.png
    - Plots/loss.png
  evaluate:
    cmd: python Code/evaluate.py
    deps:
    - Code/evaluate.py
    - Data/prepared_data/test
    - Model/model.tf.index
    metrics:
    - Metrics/f1_score.json
