prepare:
  selected_emotions: [Happy, Sad, Neutral]
train:
  classes: [Happy, Sad, Neutral]
  zoom_range: 0.1
  rotation_range: 20
  width_shift_range: 0.1
  height_shift_range: 0.1
  brightness_range: [0.5, 1.5]
  horizontal_flip: 1
  vertical_flip: 0
  class_num: 3
  image_size: 48
  batch_size: 64
  epochs: 100
  learning_rate: 0.003
  activation_func: relu
  conv2d_units: [32, 64, 128, 512, 512]
  conv2d_kernels: [3, 3, 3, 3, 3]
  pool_sizes: [2, 2, 2, 2, 2]
  dense_units: [256, 512]
  dropout: 0.1
